sudo: required

notifications:
  email: false

services:
  - docker

before_install:
  - docker build -t forkerino/docker-react -f Dockerfile.dev .

script:
  - docker run forkerino/docker-react npm run test -- --coverage

